/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// CloudTrafficQuota
    /// </summary>
    [DataContract(Name = "CloudTrafficQuota")]
    public partial class CloudTrafficQuota : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CloudTrafficQuota" /> class.
        /// </summary>
        /// <param name="currentUsage">Transferred data in bytes within the current period..</param>
        /// <param name="maximumLimit">Allowed data limit in bytes for the current period. A null value indicates an unlimited quota..</param>
        /// <param name="nextResetAt">Timestamp indicating when the current usage will reset to zero..</param>
        public CloudTrafficQuota(long currentUsage = default, long? maximumLimit = default, DateTime nextResetAt = default)
        {
            this.CurrentUsage = currentUsage;
            this.MaximumLimit = maximumLimit;
            this.NextResetAt = nextResetAt;
        }

        /// <summary>
        /// Transferred data in bytes within the current period.
        /// </summary>
        /// <value>Transferred data in bytes within the current period.</value>
        [DataMember(Name = "currentUsage", EmitDefaultValue = false)]
        public long CurrentUsage { get; set; }

        /// <summary>
        /// Allowed data limit in bytes for the current period. A null value indicates an unlimited quota.
        /// </summary>
        /// <value>Allowed data limit in bytes for the current period. A null value indicates an unlimited quota.</value>
        [DataMember(Name = "maximumLimit", EmitDefaultValue = true)]
        public long? MaximumLimit { get; set; }

        /// <summary>
        /// Timestamp indicating when the current usage will reset to zero.
        /// </summary>
        /// <value>Timestamp indicating when the current usage will reset to zero.</value>
        [DataMember(Name = "nextResetAt", EmitDefaultValue = false)]
        public DateTime NextResetAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CloudTrafficQuota {\n");
            sb.Append("  CurrentUsage: ").Append(CurrentUsage).Append("\n");
            sb.Append("  MaximumLimit: ").Append(MaximumLimit).Append("\n");
            sb.Append("  NextResetAt: ").Append(NextResetAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
