/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Defines ErrorCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorCode
    {
        /// <summary>
        /// Enum NoToken for value: no_token
        /// </summary>
        [EnumMember(Value = "no_token")]
        NoToken = 1,

        /// <summary>
        /// Enum Unauthorized for value: unauthorized
        /// </summary>
        [EnumMember(Value = "unauthorized")]
        Unauthorized = 2,

        /// <summary>
        /// Enum InvalidSession for value: invalid_session
        /// </summary>
        [EnumMember(Value = "invalid_session")]
        InvalidSession = 3,

        /// <summary>
        /// Enum TokenExpired for value: token_expired
        /// </summary>
        [EnumMember(Value = "token_expired")]
        TokenExpired = 4,

        /// <summary>
        /// Enum AuthenticationFailed for value: authentication_failed
        /// </summary>
        [EnumMember(Value = "authentication_failed")]
        AuthenticationFailed = 5,

        /// <summary>
        /// Enum AccountlessLimitReached for value: accountless_limit_reached
        /// </summary>
        [EnumMember(Value = "accountless_limit_reached")]
        AccountlessLimitReached = 6,

        /// <summary>
        /// Enum NoCapability for value: no_capability
        /// </summary>
        [EnumMember(Value = "no_capability")]
        NoCapability = 7,

        /// <summary>
        /// Enum NoCookiesCapability for value: no_cookies_capability
        /// </summary>
        [EnumMember(Value = "no_cookies_capability")]
        NoCookiesCapability = 8,

        /// <summary>
        /// Enum NoMobileCapability for value: no_mobile_capability
        /// </summary>
        [EnumMember(Value = "no_mobile_capability")]
        NoMobileCapability = 9,

        /// <summary>
        /// Enum NoProxyTestCapability for value: no_proxy_test_capability
        /// </summary>
        [EnumMember(Value = "no_proxy_test_capability")]
        NoProxyTestCapability = 10,

        /// <summary>
        /// Enum NoCloudCapability for value: no_cloud_capability
        /// </summary>
        [EnumMember(Value = "no_cloud_capability")]
        NoCloudCapability = 11,

        /// <summary>
        /// Enum NoLocalCapability for value: no_local_capability
        /// </summary>
        [EnumMember(Value = "no_local_capability")]
        NoLocalCapability = 12,

        /// <summary>
        /// Enum NoGroupsCapability for value: no_groups_capability
        /// </summary>
        [EnumMember(Value = "no_groups_capability")]
        NoGroupsCapability = 13,

        /// <summary>
        /// Enum NoHeadlessCapability for value: no_headless_capability
        /// </summary>
        [EnumMember(Value = "no_headless_capability")]
        NoHeadlessCapability = 14,

        /// <summary>
        /// Enum ProfileNotFound for value: profile_not_found
        /// </summary>
        [EnumMember(Value = "profile_not_found")]
        ProfileNotFound = 15,

        /// <summary>
        /// Enum ProfileAlreadyRunning for value: profile_already_running
        /// </summary>
        [EnumMember(Value = "profile_already_running")]
        ProfileAlreadyRunning = 16,

        /// <summary>
        /// Enum ProfileNotRunning for value: profile_not_running
        /// </summary>
        [EnumMember(Value = "profile_not_running")]
        ProfileNotRunning = 17,

        /// <summary>
        /// Enum ProfileRunning for value: profile_running
        /// </summary>
        [EnumMember(Value = "profile_running")]
        ProfileRunning = 18,

        /// <summary>
        /// Enum ProfileLocked for value: profile_locked
        /// </summary>
        [EnumMember(Value = "profile_locked")]
        ProfileLocked = 19,

        /// <summary>
        /// Enum ProfileSyncing for value: profile_syncing
        /// </summary>
        [EnumMember(Value = "profile_syncing")]
        ProfileSyncing = 20,

        /// <summary>
        /// Enum ProfileNeverStarted for value: profile_never_started
        /// </summary>
        [EnumMember(Value = "profile_never_started")]
        ProfileNeverStarted = 21,

        /// <summary>
        /// Enum BrowserEngineOutdated for value: browser_engine_outdated
        /// </summary>
        [EnumMember(Value = "browser_engine_outdated")]
        BrowserEngineOutdated = 22,

        /// <summary>
        /// Enum ProxyConnectionIssue for value: proxy_connection_issue
        /// </summary>
        [EnumMember(Value = "proxy_connection_issue")]
        ProxyConnectionIssue = 23,

        /// <summary>
        /// Enum CloudLimitReached for value: cloud_limit_reached
        /// </summary>
        [EnumMember(Value = "cloud_limit_reached")]
        CloudLimitReached = 24,

        /// <summary>
        /// Enum CloudProfileNotExportable for value: cloud_profile_not_exportable
        /// </summary>
        [EnumMember(Value = "cloud_profile_not_exportable")]
        CloudProfileNotExportable = 25,

        /// <summary>
        /// Enum ProfileAlreadyImported for value: profile_already_imported
        /// </summary>
        [EnumMember(Value = "profile_already_imported")]
        ProfileAlreadyImported = 26,

        /// <summary>
        /// Enum IncompatibleFile for value: incompatible_file
        /// </summary>
        [EnumMember(Value = "incompatible_file")]
        IncompatibleFile = 27,

        /// <summary>
        /// Enum RunningProfilesLimitReached for value: running_profiles_limit_reached
        /// </summary>
        [EnumMember(Value = "running_profiles_limit_reached")]
        RunningProfilesLimitReached = 28,

        /// <summary>
        /// Enum ProfileMinutesLimitReached for value: profile_minutes_limit_reached
        /// </summary>
        [EnumMember(Value = "profile_minutes_limit_reached")]
        ProfileMinutesLimitReached = 29,

        /// <summary>
        /// Enum DownloadedCloudProfileBytesLimitReached for value: downloaded_cloud_profile_bytes_limit_reached
        /// </summary>
        [EnumMember(Value = "downloaded_cloud_profile_bytes_limit_reached")]
        DownloadedCloudProfileBytesLimitReached = 30,

        /// <summary>
        /// Enum FolderNotFound for value: folder_not_found
        /// </summary>
        [EnumMember(Value = "folder_not_found")]
        FolderNotFound = 31,

        /// <summary>
        /// Enum DatabaseNotFound for value: database_not_found
        /// </summary>
        [EnumMember(Value = "database_not_found")]
        DatabaseNotFound = 32,

        /// <summary>
        /// Enum ValidationFailed for value: validation_failed
        /// </summary>
        [EnumMember(Value = "validation_failed")]
        ValidationFailed = 33,

        /// <summary>
        /// Enum InvalidRequest for value: invalid_request
        /// </summary>
        [EnumMember(Value = "invalid_request")]
        InvalidRequest = 34,

        /// <summary>
        /// Enum ServiceNotReady for value: service_not_ready
        /// </summary>
        [EnumMember(Value = "service_not_ready")]
        ServiceNotReady = 35,

        /// <summary>
        /// Enum RateLimitExceeded for value: rate_limit_exceeded
        /// </summary>
        [EnumMember(Value = "rate_limit_exceeded")]
        RateLimitExceeded = 36,

        /// <summary>
        /// Enum KernelDownloadLimitReached for value: kernel_download_limit_reached
        /// </summary>
        [EnumMember(Value = "kernel_download_limit_reached")]
        KernelDownloadLimitReached = 37,

        /// <summary>
        /// Enum KernelNotFound for value: kernel_not_found
        /// </summary>
        [EnumMember(Value = "kernel_not_found")]
        KernelNotFound = 38,

        /// <summary>
        /// Enum KernelInUse for value: kernel_in_use
        /// </summary>
        [EnumMember(Value = "kernel_in_use")]
        KernelInUse = 39,

        /// <summary>
        /// Enum CdpConnectionFailed for value: cdp_connection_failed
        /// </summary>
        [EnumMember(Value = "cdp_connection_failed")]
        CdpConnectionFailed = 40,

        /// <summary>
        /// Enum BrowserInstrumentationDisabled for value: browser_instrumentation_disabled
        /// </summary>
        [EnumMember(Value = "browser_instrumentation_disabled")]
        BrowserInstrumentationDisabled = 41,

        /// <summary>
        /// Enum VncNotSupported for value: vnc_not_supported
        /// </summary>
        [EnumMember(Value = "vnc_not_supported")]
        VncNotSupported = 42,

        /// <summary>
        /// Enum UploadFailed for value: upload_failed
        /// </summary>
        [EnumMember(Value = "upload_failed")]
        UploadFailed = 43,

        /// <summary>
        /// Enum UnexpectedError for value: unexpected_error
        /// </summary>
        [EnumMember(Value = "unexpected_error")]
        UnexpectedError = 44
    }

}
