/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// ProblemResponse
    /// </summary>
    [DataContract(Name = "ProblemResponse")]
    public partial class ProblemResponse : IValidatableObject
    {

        /// <summary>
        /// A machine-readable error code that identifies the specific error condition. This can be used by clients to programmatically handle different error scenarios.
        /// </summary>
        /// <value>A machine-readable error code that identifies the specific error condition. This can be used by clients to programmatically handle different error scenarios.</value>
        [DataMember(Name = "errorCode", IsRequired = true, EmitDefaultValue = true)]
        public ErrorCode ErrorCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProblemResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProblemResponse()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProblemResponse" /> class.
        /// </summary>
        /// <param name="status">The HTTP status code generated by the origin server for this occurrence of the problem. (required).</param>
        /// <param name="errorCode">A machine-readable error code that identifies the specific error condition. This can be used by clients to programmatically handle different error scenarios. (required).</param>
        /// <param name="type">A URI reference that identifies the problem type..</param>
        /// <param name="title">A short, human-readable summary of the problem type. (required).</param>
        /// <param name="detail">A human-readable explanation specific to this occurrence of the problem..</param>
        /// <param name="instance">A URI reference that identifies the specific occurrence of the problem..</param>
        /// <param name="errors">The validation errors, if any. The keys are field names and the values are arrays of error messages..</param>
        public ProblemResponse(int status = default, ErrorCode errorCode = default, string type = default, string title = default, string detail = default, string instance = default, Dictionary<string, List<string>> errors = default)
        {
            this.Status = status;
            this.ErrorCode = errorCode;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for ProblemResponse and cannot be null");
            }
            this.Title = title;
            this.Type = type;
            this.Detail = detail;
            this.Instance = instance;
            this.Errors = errors;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        /// <value>The HTTP status code generated by the origin server for this occurrence of the problem.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public int Status { get; set; }

        /// <summary>
        /// A URI reference that identifies the problem type.
        /// </summary>
        /// <value>A URI reference that identifies the problem type.</value>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// </summary>
        /// <value>A short, human-readable summary of the problem type.</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        /// <value>A human-readable explanation specific to this occurrence of the problem.</value>
        [DataMember(Name = "detail", EmitDefaultValue = true)]
        public string Detail { get; set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// </summary>
        /// <value>A URI reference that identifies the specific occurrence of the problem.</value>
        [DataMember(Name = "instance", EmitDefaultValue = true)]
        public string Instance { get; set; }

        /// <summary>
        /// The validation errors, if any. The keys are field names and the values are arrays of error messages.
        /// </summary>
        /// <value>The validation errors, if any. The keys are field names and the values are arrays of error messages.</value>
        [DataMember(Name = "errors", EmitDefaultValue = true)]
        public Dictionary<string, List<string>> Errors { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProblemResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("  Instance: ").Append(Instance).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
