/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Defines ProxyValidationStep
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProxyValidationStep
    {
        /// <summary>
        /// Enum SshConnection for value: ssh_connection
        /// </summary>
        [EnumMember(Value = "ssh_connection")]
        SshConnection = 1,

        /// <summary>
        /// Enum DirectPing for value: direct_ping
        /// </summary>
        [EnumMember(Value = "direct_ping")]
        DirectPing = 2,

        /// <summary>
        /// Enum DirectHttps for value: direct_https
        /// </summary>
        [EnumMember(Value = "direct_https")]
        DirectHttps = 3,

        /// <summary>
        /// Enum ProxyIpv4 for value: proxy_ipv4
        /// </summary>
        [EnumMember(Value = "proxy_ipv4")]
        ProxyIpv4 = 4,

        /// <summary>
        /// Enum ProxyIpv6 for value: proxy_ipv6
        /// </summary>
        [EnumMember(Value = "proxy_ipv6")]
        ProxyIpv6 = 5,

        /// <summary>
        /// Enum ProxyWebsite for value: proxy_website
        /// </summary>
        [EnumMember(Value = "proxy_website")]
        ProxyWebsite = 6,

        /// <summary>
        /// Enum ProxyLocation for value: proxy_location
        /// </summary>
        [EnumMember(Value = "proxy_location")]
        ProxyLocation = 7
    }

}
