/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// ProxyTestStepResponse
    /// </summary>
    [DataContract(Name = "ProxyTestStepResponse")]
    public partial class ProxyTestStepResponse : IValidatableObject
    {

        /// <summary>
        /// Identifier of the executed test step.
        /// </summary>
        /// <value>Identifier of the executed test step.</value>
        [DataMember(Name = "step", IsRequired = true, EmitDefaultValue = true)]
        public ProxyValidationStep Step { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProxyTestStepResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProxyTestStepResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProxyTestStepResponse" /> class.
        /// </summary>
        /// <param name="step">Identifier of the executed test step. (required).</param>
        /// <param name="name">The name of the executed test case. (required).</param>
        /// <param name="successful">Whether the test was successful or not. (required).</param>
        /// <param name="comment">Any additional details about the test case, such as error messages..</param>
        public ProxyTestStepResponse(ProxyValidationStep step = default, string name = default, bool successful = default, string comment = default)
        {
            this.Step = step;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ProxyTestStepResponse and cannot be null");
            }
            this.Name = name;
            this.Successful = successful;
            this.Comment = comment;
        }

        /// <summary>
        /// The name of the executed test case.
        /// </summary>
        /// <value>The name of the executed test case.</value>
        /*
        <example>Testing direct internet connectivity by pinging a remote host</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Whether the test was successful or not.
        /// </summary>
        /// <value>Whether the test was successful or not.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "successful", IsRequired = true, EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// Any additional details about the test case, such as error messages.
        /// </summary>
        /// <value>Any additional details about the test case, such as error messages.</value>
        /*
        <example>Proxy authentication failed</example>
        */
        [DataMember(Name = "comment", EmitDefaultValue = true)]
        public string Comment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProxyTestStepResponse {\n");
            sb.Append("  Step: ").Append(Step).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
