/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// Summarizes the overall outcome of a proxy connectivity test. Possible values:  &#39;success&#39;: Every test step passed.  &#39;partial_success&#39;: The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.  &#39;failure&#39;: None of the connectivity checks succeeded.
    /// </summary>
    /// <value>Summarizes the overall outcome of a proxy connectivity test. Possible values:  &#39;success&#39;: Every test step passed.  &#39;partial_success&#39;: The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.  &#39;failure&#39;: None of the connectivity checks succeeded.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProxyTestResultStatus
    {
        /// <summary>
        /// Enum Success for value: success
        /// </summary>
        [EnumMember(Value = "success")]
        Success = 1,

        /// <summary>
        /// Enum PartialSuccess for value: partial_success
        /// </summary>
        [EnumMember(Value = "partial_success")]
        PartialSuccess = 2,

        /// <summary>
        /// Enum Failure for value: failure
        /// </summary>
        [EnumMember(Value = "failure")]
        Failure = 3
    }

}
