/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// RunningProfiles
    /// </summary>
    [DataContract(Name = "RunningProfiles")]
    public partial class RunningProfiles : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunningProfiles" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RunningProfiles() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunningProfiles" /> class.
        /// </summary>
        /// <param name="user">Current usage and maximum limit of running manual and automated profiles for the logged-in user. (required).</param>
        /// <param name="tenant">Current usage and maximum limit of running manual and automated profiles across the tenant. (required).</param>
        public RunningProfiles(RunningProfilesStatistics user = default, RunningProfilesStatistics tenant = default)
        {
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for RunningProfiles and cannot be null");
            }
            this.User = user;
            // to ensure "tenant" is required (not null)
            if (tenant == null)
            {
                throw new ArgumentNullException("tenant is a required property for RunningProfiles and cannot be null");
            }
            this.Tenant = tenant;
        }

        /// <summary>
        /// Current usage and maximum limit of running manual and automated profiles for the logged-in user.
        /// </summary>
        /// <value>Current usage and maximum limit of running manual and automated profiles for the logged-in user.</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public RunningProfilesStatistics User { get; set; }

        /// <summary>
        /// Current usage and maximum limit of running manual and automated profiles across the tenant.
        /// </summary>
        /// <value>Current usage and maximum limit of running manual and automated profiles across the tenant.</value>
        [DataMember(Name = "tenant", IsRequired = true, EmitDefaultValue = true)]
        public RunningProfilesStatistics Tenant { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunningProfiles {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  Tenant: ").Append(Tenant).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
