/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// RunningProfilesStatistics
    /// </summary>
    [DataContract(Name = "RunningProfilesStatistics")]
    public partial class RunningProfilesStatistics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunningProfilesStatistics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RunningProfilesStatistics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunningProfilesStatistics" /> class.
        /// </summary>
        /// <param name="automated">Quota usage of the profiles that are running with an automation framework. (required).</param>
        /// <param name="manual">Quota usage of the profiles that are running manually (were started from GUI or API). (required).</param>
        /// <param name="total">Quota usage of the profiles that are running either manually or with an automation framework. (required).</param>
        public RunningProfilesStatistics(QuotaStatistics automated = default, QuotaStatistics manual = default, QuotaStatistics total = default)
        {
            // to ensure "automated" is required (not null)
            if (automated == null)
            {
                throw new ArgumentNullException("automated is a required property for RunningProfilesStatistics and cannot be null");
            }
            this.Automated = automated;
            // to ensure "manual" is required (not null)
            if (manual == null)
            {
                throw new ArgumentNullException("manual is a required property for RunningProfilesStatistics and cannot be null");
            }
            this.Manual = manual;
            // to ensure "total" is required (not null)
            if (total == null)
            {
                throw new ArgumentNullException("total is a required property for RunningProfilesStatistics and cannot be null");
            }
            this.Total = total;
        }

        /// <summary>
        /// Quota usage of the profiles that are running with an automation framework.
        /// </summary>
        /// <value>Quota usage of the profiles that are running with an automation framework.</value>
        [DataMember(Name = "automated", IsRequired = true, EmitDefaultValue = true)]
        public QuotaStatistics Automated { get; set; }

        /// <summary>
        /// Quota usage of the profiles that are running manually (were started from GUI or API).
        /// </summary>
        /// <value>Quota usage of the profiles that are running manually (were started from GUI or API).</value>
        [DataMember(Name = "manual", IsRequired = true, EmitDefaultValue = true)]
        public QuotaStatistics Manual { get; set; }

        /// <summary>
        /// Quota usage of the profiles that are running either manually or with an automation framework.
        /// </summary>
        /// <value>Quota usage of the profiles that are running either manually or with an automation framework.</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public QuotaStatistics Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunningProfilesStatistics {\n");
            sb.Append("  Automated: ").Append(Automated).Append("\n");
            sb.Append("  Manual: ").Append(Manual).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
