/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// TestProxyResponse
    /// </summary>
    [DataContract(Name = "TestProxyResponse")]
    public partial class TestProxyResponse : IValidatableObject
    {

        /// <summary>
        /// Summarizes the overall outcome of a proxy connectivity test. Possible values:  &#39;success&#39;: Every test step passed.  &#39;partial_success&#39;: The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.  &#39;failure&#39;: None of the connectivity checks succeeded.
        /// </summary>
        /// <value>Summarizes the overall outcome of a proxy connectivity test. Possible values:  &#39;success&#39;: Every test step passed.  &#39;partial_success&#39;: The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.  &#39;failure&#39;: None of the connectivity checks succeeded.</value>
        [DataMember(Name = "result", IsRequired = true, EmitDefaultValue = true)]
        public ProxyTestResultStatus Result { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestProxyResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestProxyResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestProxyResponse" /> class.
        /// </summary>
        /// <param name="result">Summarizes the overall outcome of a proxy connectivity test. Possible values:  &#39;success&#39;: Every test step passed.  &#39;partial_success&#39;: The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.  &#39;failure&#39;: None of the connectivity checks succeeded. (required).</param>
        /// <param name="steps">A list containing each individual test step performed while testing the proxy connection. (required).</param>
        public TestProxyResponse(ProxyTestResultStatus result = default, List<ProxyTestStepResponse> steps = default)
        {
            this.Result = result;
            // to ensure "steps" is required (not null)
            if (steps == null)
            {
                throw new ArgumentNullException("steps is a required property for TestProxyResponse and cannot be null");
            }
            this.Steps = steps;
        }

        /// <summary>
        /// A list containing each individual test step performed while testing the proxy connection.
        /// </summary>
        /// <value>A list containing each individual test step performed while testing the proxy connection.</value>
        [DataMember(Name = "steps", IsRequired = true, EmitDefaultValue = true)]
        public List<ProxyTestStepResponse> Steps { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestProxyResponse {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Steps: ").Append(Steps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
