/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kameleo.LocalApiClient.Client.OpenAPIDateConverter;

namespace Kameleo.LocalApiClient.Model
{
    /// <summary>
    /// TestProxyRequest
    /// </summary>
    [DataContract(Name = "TestProxyRequest")]
    public partial class TestProxyRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestProxyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestProxyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestProxyRequest" /> class.
        /// </summary>
        /// <param name="proxy">Sets the Proxy connection settings to test. Values can be &#39;none&#39;, &#39;http&#39;, &#39;socks5&#39;, &#39;ssh&#39;. When it is not set to none, a server must be  provided. (required).</param>
        public TestProxyRequest(ProxyChoice proxy = default)
        {
            // to ensure "proxy" is required (not null)
            if (proxy == null)
            {
                throw new ArgumentNullException("proxy is a required property for TestProxyRequest and cannot be null");
            }
            this.Proxy = proxy;
        }

        /// <summary>
        /// Sets the Proxy connection settings to test. Values can be &#39;none&#39;, &#39;http&#39;, &#39;socks5&#39;, &#39;ssh&#39;. When it is not set to none, a server must be  provided.
        /// </summary>
        /// <value>Sets the Proxy connection settings to test. Values can be &#39;none&#39;, &#39;http&#39;, &#39;socks5&#39;, &#39;ssh&#39;. When it is not set to none, a server must be  provided.</value>
        [DataMember(Name = "proxy", IsRequired = true, EmitDefaultValue = true)]
        public ProxyChoice Proxy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestProxyRequest {\n");
            sb.Append("  Proxy: ").Append(Proxy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
