/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ProblemResponse, TestProxyRequest, TestProxyResponse, UserInfoResponse } from "../models/index";
import {
    ProblemResponseFromJSON,
    ProblemResponseToJSON,
    TestProxyRequestFromJSON,
    TestProxyRequestToJSON,
    TestProxyResponseFromJSON,
    TestProxyResponseToJSON,
    UserInfoResponseFromJSON,
    UserInfoResponseToJSON,
} from "../models/index";

export interface TestProxyOperationRequest {
    testProxyRequest?: TestProxyRequest;
}

/**
 *
 */
export class GeneralApi extends runtime.BaseAPI {
    /**
     * Fetch detailed information about your user account.
     */
    async getUserInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/general/user-info`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoResponseFromJSON(jsonValue));
    }

    /**
     * Fetch detailed information about your user account.
     */
    async getUserInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfoResponse> {
        const response = await this.getUserInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Health check request to test if Kameleo has been started and accepting connections.
     */
    async healthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/general/healthcheck`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Health check request to test if Kameleo has been started and accepting connections.
     */
    async healthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.healthcheckRaw(initOverrides);
    }

    /**
     * Terminate your current Kameleo session by deauthenticating and exiting the Engine. Use this to safely close your session and release any  associated resources.
     */
    async terminateApplicationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/general/terminate`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Terminate your current Kameleo session by deauthenticating and exiting the Engine. Use this to safely close your session and release any  associated resources.
     */
    async terminateApplication(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.terminateApplicationRaw(initOverrides);
    }

    /**
     * Tests the given proxy connection and returns every individual test step together with an overall summary. The summary is \'success\' when  every step passes, \'partial_success\' when the website could be reached through at least one of IPv4, IPv6 or DNS name and the IP location  lookup also succeeded, otherwise \'failure\'.
     */
    async testProxyRaw(
        requestParameters: TestProxyOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<TestProxyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        let urlPath = `/general/test-proxy`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: TestProxyRequestToJSON(requestParameters["testProxyRequest"]),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => TestProxyResponseFromJSON(jsonValue));
    }

    /**
     * Tests the given proxy connection and returns every individual test step together with an overall summary. The summary is \'success\' when  every step passes, \'partial_success\' when the website could be reached through at least one of IPv4, IPv6 or DNS name and the IP location  lookup also succeeded, otherwise \'failure\'.
     */
    async testProxy(
        testProxyRequest?: TestProxyRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<TestProxyResponse> {
        const response = await this.testProxyRaw({ testProxyRequest: testProxyRequest }, initOverrides);
        return await response.value();
    }
}
