/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 4.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CloudTrafficQuota
 */
export interface CloudTrafficQuota {
    /**
     * Transferred data in bytes within the current period.
     * @type {number}
     * @memberof CloudTrafficQuota
     */
    currentUsage?: number;
    /**
     * Allowed data limit in bytes for the current period. A null value indicates an unlimited quota.
     * @type {number}
     * @memberof CloudTrafficQuota
     */
    maximumLimit?: number | null;
    /**
     * Timestamp indicating when the current usage will reset to zero.
     * @type {Date}
     * @memberof CloudTrafficQuota
     */
    nextResetAt?: Date;
}

/**
 * Check if a given object implements the CloudTrafficQuota interface.
 */
export function instanceOfCloudTrafficQuota(value: object): value is CloudTrafficQuota {
    return true;
}

export function CloudTrafficQuotaFromJSON(json: any): CloudTrafficQuota {
    return CloudTrafficQuotaFromJSONTyped(json, false);
}

export function CloudTrafficQuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudTrafficQuota {
    if (json == null) {
        return json;
    }
    return {
        currentUsage: json["currentUsage"] == null ? undefined : json["currentUsage"],
        maximumLimit: json["maximumLimit"] == null ? undefined : json["maximumLimit"],
        nextResetAt: json["nextResetAt"] == null ? undefined : new Date(json["nextResetAt"]),
    };
}

export function CloudTrafficQuotaToJSON(json: any): CloudTrafficQuota {
    return CloudTrafficQuotaToJSONTyped(json, false);
}

export function CloudTrafficQuotaToJSONTyped(value?: CloudTrafficQuota | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        currentUsage: value["currentUsage"],
        maximumLimit: value["maximumLimit"],
        nextResetAt: value["nextResetAt"] == null ? value["nextResetAt"] : value["nextResetAt"].toISOString(),
    };
}
