/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ErrorCode = {
    NoToken: "no_token",
    Unauthorized: "unauthorized",
    InvalidSession: "invalid_session",
    TokenExpired: "token_expired",
    AuthenticationFailed: "authentication_failed",
    AccountlessLimitReached: "accountless_limit_reached",
    NoCapability: "no_capability",
    NoCookiesCapability: "no_cookies_capability",
    NoMobileCapability: "no_mobile_capability",
    NoProxyTestCapability: "no_proxy_test_capability",
    NoCloudCapability: "no_cloud_capability",
    NoLocalCapability: "no_local_capability",
    NoGroupsCapability: "no_groups_capability",
    NoHeadlessCapability: "no_headless_capability",
    ProfileNotFound: "profile_not_found",
    ProfileAlreadyRunning: "profile_already_running",
    ProfileNotRunning: "profile_not_running",
    ProfileRunning: "profile_running",
    ProfileLocked: "profile_locked",
    ProfileSyncing: "profile_syncing",
    ProfileNeverStarted: "profile_never_started",
    BrowserEngineOutdated: "browser_engine_outdated",
    ProxyConnectionIssue: "proxy_connection_issue",
    CloudLimitReached: "cloud_limit_reached",
    CloudProfileNotExportable: "cloud_profile_not_exportable",
    ProfileAlreadyImported: "profile_already_imported",
    IncompatibleFile: "incompatible_file",
    RunningProfilesLimitReached: "running_profiles_limit_reached",
    RunningMobileProfilesLimitReached: "running_mobile_profiles_limit_reached",
    ProfileMinutesLimitReached: "profile_minutes_limit_reached",
    DownloadedCloudProfileBytesLimitReached: "downloaded_cloud_profile_bytes_limit_reached",
    FolderNotFound: "folder_not_found",
    DatabaseNotFound: "database_not_found",
    ValidationFailed: "validation_failed",
    InvalidRequest: "invalid_request",
    ServiceNotReady: "service_not_ready",
    RateLimitExceeded: "rate_limit_exceeded",
    KernelDownloadLimitReached: "kernel_download_limit_reached",
    KernelNotFound: "kernel_not_found",
    KernelInUse: "kernel_in_use",
    CdpConnectionFailed: "cdp_connection_failed",
    BrowserInstrumentationDisabled: "browser_instrumentation_disabled",
    VncNotSupported: "vnc_not_supported",
    UploadFailed: "upload_failed",
    UnexpectedError: "unexpected_error",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export function instanceOfErrorCode(value: any): boolean {
    for (const key in ErrorCode) {
        if (Object.prototype.hasOwnProperty.call(ErrorCode, key)) {
            if (ErrorCode[key as keyof typeof ErrorCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

export function ErrorCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): ErrorCode {
    return value as ErrorCode;
}
