/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ErrorCode } from "./ErrorCode";
import { ErrorCodeFromJSON, ErrorCodeFromJSONTyped, ErrorCodeToJSON, ErrorCodeToJSONTyped } from "./ErrorCode";

/**
 *
 * @export
 * @interface ProblemResponse
 */
export interface ProblemResponse {
    [key: string]: any | any;
    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     * @type {number}
     * @memberof ProblemResponse
     */
    status: number;
    /**
     * A machine-readable error code that identifies the specific error condition. This can be used by clients to programmatically handle different error scenarios.
     * @type {ErrorCode}
     * @memberof ProblemResponse
     */
    errorCode: ErrorCode;
    /**
     * A URI reference that identifies the problem type.
     * @type {string}
     * @memberof ProblemResponse
     */
    type?: string | null;
    /**
     * A short, human-readable summary of the problem type.
     * @type {string}
     * @memberof ProblemResponse
     */
    title: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof ProblemResponse
     */
    detail?: string | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * @type {string}
     * @memberof ProblemResponse
     */
    instance?: string | null;
    /**
     * The validation errors, if any. The keys are field names and the values are arrays of error messages.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ProblemResponse
     */
    errors?: { [key: string]: Array<string> } | null;
}

/**
 * Check if a given object implements the ProblemResponse interface.
 */
export function instanceOfProblemResponse(value: object): value is ProblemResponse {
    if (!("status" in value) || value["status"] === undefined) return false;
    if (!("errorCode" in value) || value["errorCode"] === undefined) return false;
    if (!("title" in value) || value["title"] === undefined) return false;
    return true;
}

export function ProblemResponseFromJSON(json: any): ProblemResponse {
    return ProblemResponseFromJSONTyped(json, false);
}

export function ProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemResponse {
    if (json == null) {
        return json;
    }
    return {
        ...json,
        status: json["status"],
        errorCode: ErrorCodeFromJSON(json["errorCode"]),
        type: json["type"] == null ? undefined : json["type"],
        title: json["title"],
        detail: json["detail"] == null ? undefined : json["detail"],
        instance: json["instance"] == null ? undefined : json["instance"],
        errors: json["errors"] == null ? undefined : json["errors"],
    };
}

export function ProblemResponseToJSON(json: any): ProblemResponse {
    return ProblemResponseToJSONTyped(json, false);
}

export function ProblemResponseToJSONTyped(value?: ProblemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...value,
        status: value["status"],
        errorCode: ErrorCodeToJSON(value["errorCode"]),
        type: value["type"],
        title: value["title"],
        detail: value["detail"],
        instance: value["instance"],
        errors: value["errors"],
    };
}
