/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ProxyValidationStep } from "./ProxyValidationStep";
import {
    ProxyValidationStepFromJSON,
    ProxyValidationStepFromJSONTyped,
    ProxyValidationStepToJSON,
    ProxyValidationStepToJSONTyped,
} from "./ProxyValidationStep";

/**
 *
 * @export
 * @interface ProxyTestStepResponse
 */
export interface ProxyTestStepResponse {
    /**
     * Identifier of the executed test step.
     * @type {ProxyValidationStep}
     * @memberof ProxyTestStepResponse
     */
    step: ProxyValidationStep;
    /**
     * The name of the executed test case.
     * @type {string}
     * @memberof ProxyTestStepResponse
     */
    name: string;
    /**
     * Whether the test was successful or not.
     * @type {boolean}
     * @memberof ProxyTestStepResponse
     */
    successful: boolean;
    /**
     * Any additional details about the test case, such as error messages.
     * @type {string}
     * @memberof ProxyTestStepResponse
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the ProxyTestStepResponse interface.
 */
export function instanceOfProxyTestStepResponse(value: object): value is ProxyTestStepResponse {
    if (!("step" in value) || value["step"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("successful" in value) || value["successful"] === undefined) return false;
    return true;
}

export function ProxyTestStepResponseFromJSON(json: any): ProxyTestStepResponse {
    return ProxyTestStepResponseFromJSONTyped(json, false);
}

export function ProxyTestStepResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxyTestStepResponse {
    if (json == null) {
        return json;
    }
    return {
        step: ProxyValidationStepFromJSON(json["step"]),
        name: json["name"],
        successful: json["successful"],
        comment: json["comment"] == null ? undefined : json["comment"],
    };
}

export function ProxyTestStepResponseToJSON(json: any): ProxyTestStepResponse {
    return ProxyTestStepResponseToJSONTyped(json, false);
}

export function ProxyTestStepResponseToJSONTyped(value?: ProxyTestStepResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        step: ProxyValidationStepToJSON(value["step"]),
        name: value["name"],
        successful: value["successful"],
        comment: value["comment"],
    };
}
