/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ProxyValidationStep = {
    SshConnection: "ssh_connection",
    DirectPing: "direct_ping",
    DirectHttps: "direct_https",
    ProxyIpv4: "proxy_ipv4",
    ProxyIpv6: "proxy_ipv6",
    ProxyWebsite: "proxy_website",
    ProxyLocation: "proxy_location",
} as const;
export type ProxyValidationStep = (typeof ProxyValidationStep)[keyof typeof ProxyValidationStep];

export function instanceOfProxyValidationStep(value: any): boolean {
    for (const key in ProxyValidationStep) {
        if (Object.prototype.hasOwnProperty.call(ProxyValidationStep, key)) {
            if (ProxyValidationStep[key as keyof typeof ProxyValidationStep] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProxyValidationStepFromJSON(json: any): ProxyValidationStep {
    return ProxyValidationStepFromJSONTyped(json, false);
}

export function ProxyValidationStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxyValidationStep {
    return json as ProxyValidationStep;
}

export function ProxyValidationStepToJSON(value?: ProxyValidationStep | null): any {
    return value as any;
}

export function ProxyValidationStepToJSONTyped(value: any, ignoreDiscriminator: boolean): ProxyValidationStep {
    return value as ProxyValidationStep;
}
