/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Summarizes the overall outcome of a proxy connectivity test. Possible values:
 * 'success': Every test step passed.
 * 'partial_success': The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.
 * 'failure': None of the connectivity checks succeeded.
 * @export
 */
export const ProxyTestResultStatus = {
    Success: "success",
    PartialSuccess: "partial_success",
    Failure: "failure",
} as const;
export type ProxyTestResultStatus = (typeof ProxyTestResultStatus)[keyof typeof ProxyTestResultStatus];

export function instanceOfProxyTestResultStatus(value: any): boolean {
    for (const key in ProxyTestResultStatus) {
        if (Object.prototype.hasOwnProperty.call(ProxyTestResultStatus, key)) {
            if (ProxyTestResultStatus[key as keyof typeof ProxyTestResultStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProxyTestResultStatusFromJSON(json: any): ProxyTestResultStatus {
    return ProxyTestResultStatusFromJSONTyped(json, false);
}

export function ProxyTestResultStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxyTestResultStatus {
    return json as ProxyTestResultStatus;
}

export function ProxyTestResultStatusToJSON(value?: ProxyTestResultStatus | null): any {
    return value as any;
}

export function ProxyTestResultStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ProxyTestResultStatus {
    return value as ProxyTestResultStatus;
}
