/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { QuotaStatistics } from "./QuotaStatistics";
import {
    QuotaStatisticsFromJSON,
    QuotaStatisticsFromJSONTyped,
    QuotaStatisticsToJSON,
    QuotaStatisticsToJSONTyped,
} from "./QuotaStatistics";

/**
 *
 * @export
 * @interface RunningProfilesStatistics
 */
export interface RunningProfilesStatistics {
    /**
     * Quota usage of the profiles that are running with an automation framework.
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    automated: QuotaStatistics;
    /**
     * Quota usage of the profiles that are running manually (were started from GUI or API).
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    manual: QuotaStatistics;
    /**
     * Quota usage of the profiles having mobile fingerprints.
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    mobile: QuotaStatistics;
    /**
     * Quota usage of the profiles that are running either manually or with an automation framework.
     * @type {QuotaStatistics}
     * @memberof RunningProfilesStatistics
     */
    total: QuotaStatistics;
}

/**
 * Check if a given object implements the RunningProfilesStatistics interface.
 */
export function instanceOfRunningProfilesStatistics(value: object): value is RunningProfilesStatistics {
    if (!("automated" in value) || value["automated"] === undefined) return false;
    if (!("manual" in value) || value["manual"] === undefined) return false;
    if (!("mobile" in value) || value["mobile"] === undefined) return false;
    if (!("total" in value) || value["total"] === undefined) return false;
    return true;
}

export function RunningProfilesStatisticsFromJSON(json: any): RunningProfilesStatistics {
    return RunningProfilesStatisticsFromJSONTyped(json, false);
}

export function RunningProfilesStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunningProfilesStatistics {
    if (json == null) {
        return json;
    }
    return {
        automated: QuotaStatisticsFromJSON(json["automated"]),
        manual: QuotaStatisticsFromJSON(json["manual"]),
        mobile: QuotaStatisticsFromJSON(json["mobile"]),
        total: QuotaStatisticsFromJSON(json["total"]),
    };
}

export function RunningProfilesStatisticsToJSON(json: any): RunningProfilesStatistics {
    return RunningProfilesStatisticsToJSONTyped(json, false);
}

export function RunningProfilesStatisticsToJSONTyped(value?: RunningProfilesStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        automated: QuotaStatisticsToJSON(value["automated"]),
        manual: QuotaStatisticsToJSON(value["manual"]),
        mobile: QuotaStatisticsToJSON(value["mobile"]),
        total: QuotaStatisticsToJSON(value["total"]),
    };
}
