/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RunningProfilesStatistics } from "./RunningProfilesStatistics";
import {
    RunningProfilesStatisticsFromJSON,
    RunningProfilesStatisticsFromJSONTyped,
    RunningProfilesStatisticsToJSON,
    RunningProfilesStatisticsToJSONTyped,
} from "./RunningProfilesStatistics";

/**
 *
 * @export
 * @interface RunningProfiles
 */
export interface RunningProfiles {
    /**
     * Current usage and maximum limit of running manual and automated profiles for the logged-in user.
     * @type {RunningProfilesStatistics}
     * @memberof RunningProfiles
     */
    user: RunningProfilesStatistics;
    /**
     * Current usage and maximum limit of running manual and automated profiles across the tenant.
     * @type {RunningProfilesStatistics}
     * @memberof RunningProfiles
     */
    tenant: RunningProfilesStatistics;
}

/**
 * Check if a given object implements the RunningProfiles interface.
 */
export function instanceOfRunningProfiles(value: object): value is RunningProfiles {
    if (!("user" in value) || value["user"] === undefined) return false;
    if (!("tenant" in value) || value["tenant"] === undefined) return false;
    return true;
}

export function RunningProfilesFromJSON(json: any): RunningProfiles {
    return RunningProfilesFromJSONTyped(json, false);
}

export function RunningProfilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunningProfiles {
    if (json == null) {
        return json;
    }
    return {
        user: RunningProfilesStatisticsFromJSON(json["user"]),
        tenant: RunningProfilesStatisticsFromJSON(json["tenant"]),
    };
}

export function RunningProfilesToJSON(json: any): RunningProfiles {
    return RunningProfilesToJSONTyped(json, false);
}

export function RunningProfilesToJSONTyped(value?: RunningProfiles | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        user: RunningProfilesStatisticsToJSON(value["user"]),
        tenant: RunningProfilesStatisticsToJSON(value["tenant"]),
    };
}
