/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ProxyChoice } from "./ProxyChoice";
import { ProxyChoiceFromJSON, ProxyChoiceFromJSONTyped, ProxyChoiceToJSON, ProxyChoiceToJSONTyped } from "./ProxyChoice";

/**
 *
 * @export
 * @interface TestProxyRequest
 */
export interface TestProxyRequest {
    /**
     * Sets the Proxy connection settings to test. Values can be 'none', 'http', 'socks5', 'ssh'. When it is not set to none, a server must be
     * provided.
     * @type {ProxyChoice}
     * @memberof TestProxyRequest
     */
    proxy: ProxyChoice;
}

/**
 * Check if a given object implements the TestProxyRequest interface.
 */
export function instanceOfTestProxyRequest(value: object): value is TestProxyRequest {
    if (!("proxy" in value) || value["proxy"] === undefined) return false;
    return true;
}

export function TestProxyRequestFromJSON(json: any): TestProxyRequest {
    return TestProxyRequestFromJSONTyped(json, false);
}

export function TestProxyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestProxyRequest {
    if (json == null) {
        return json;
    }
    return {
        proxy: ProxyChoiceFromJSON(json["proxy"]),
    };
}

export function TestProxyRequestToJSON(json: any): TestProxyRequest {
    return TestProxyRequestToJSONTyped(json, false);
}

export function TestProxyRequestToJSONTyped(value?: TestProxyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        proxy: ProxyChoiceToJSON(value["proxy"]),
    };
}
