/* tslint:disable */
/* eslint-disable */
/**
 * kameleo-local-api
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ProxyTestStepResponse } from "./ProxyTestStepResponse";
import {
    ProxyTestStepResponseFromJSON,
    ProxyTestStepResponseFromJSONTyped,
    ProxyTestStepResponseToJSON,
    ProxyTestStepResponseToJSONTyped,
} from "./ProxyTestStepResponse";
import type { ProxyTestResultStatus } from "./ProxyTestResultStatus";
import {
    ProxyTestResultStatusFromJSON,
    ProxyTestResultStatusFromJSONTyped,
    ProxyTestResultStatusToJSON,
    ProxyTestResultStatusToJSONTyped,
} from "./ProxyTestResultStatus";

/**
 *
 * @export
 * @interface TestProxyResponse
 */
export interface TestProxyResponse {
    /**
     * Summarizes the overall outcome of a proxy connectivity test. Possible values:
     * 'success': Every test step passed.
     * 'partial_success': The website could be reached through at least one of IPv4, IPv6 or DNS name, and the IP location lookup succeeded.
     * 'failure': None of the connectivity checks succeeded.
     * @type {ProxyTestResultStatus}
     * @memberof TestProxyResponse
     */
    result: ProxyTestResultStatus;
    /**
     * A list containing each individual test step performed while testing the proxy connection.
     * @type {Array<ProxyTestStepResponse>}
     * @memberof TestProxyResponse
     */
    steps: Array<ProxyTestStepResponse>;
}

/**
 * Check if a given object implements the TestProxyResponse interface.
 */
export function instanceOfTestProxyResponse(value: object): value is TestProxyResponse {
    if (!("result" in value) || value["result"] === undefined) return false;
    if (!("steps" in value) || value["steps"] === undefined) return false;
    return true;
}

export function TestProxyResponseFromJSON(json: any): TestProxyResponse {
    return TestProxyResponseFromJSONTyped(json, false);
}

export function TestProxyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestProxyResponse {
    if (json == null) {
        return json;
    }
    return {
        result: ProxyTestResultStatusFromJSON(json["result"]),
        steps: (json["steps"] as Array<any>).map(ProxyTestStepResponseFromJSON),
    };
}

export function TestProxyResponseToJSON(json: any): TestProxyResponse {
    return TestProxyResponseToJSONTyped(json, false);
}

export function TestProxyResponseToJSONTyped(value?: TestProxyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        result: ProxyTestResultStatusToJSON(value["result"]),
        steps: (value["steps"] as Array<any>).map(ProxyTestStepResponseToJSON),
    };
}
