# coding: utf-8

"""
    kameleo-local-api

    You can use the following API endpoints to communicate with the local running Kameleo programmatically.

    The version of the OpenAPI document: 5.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    ErrorCode
    """

    """
    allowed enum values
    """
    NO_TOKEN = 'no_token'
    UNAUTHORIZED = 'unauthorized'
    INVALID_SESSION = 'invalid_session'
    TOKEN_EXPIRED = 'token_expired'
    AUTHENTICATION_FAILED = 'authentication_failed'
    ACCOUNTLESS_LIMIT_REACHED = 'accountless_limit_reached'
    NO_CAPABILITY = 'no_capability'
    NO_COOKIES_CAPABILITY = 'no_cookies_capability'
    NO_MOBILE_CAPABILITY = 'no_mobile_capability'
    NO_PROXY_TEST_CAPABILITY = 'no_proxy_test_capability'
    NO_CLOUD_CAPABILITY = 'no_cloud_capability'
    NO_LOCAL_CAPABILITY = 'no_local_capability'
    NO_GROUPS_CAPABILITY = 'no_groups_capability'
    NO_HEADLESS_CAPABILITY = 'no_headless_capability'
    PROFILE_NOT_FOUND = 'profile_not_found'
    PROFILE_ALREADY_RUNNING = 'profile_already_running'
    PROFILE_NOT_RUNNING = 'profile_not_running'
    PROFILE_RUNNING = 'profile_running'
    PROFILE_LOCKED = 'profile_locked'
    PROFILE_SYNCING = 'profile_syncing'
    PROFILE_NEVER_STARTED = 'profile_never_started'
    BROWSER_ENGINE_OUTDATED = 'browser_engine_outdated'
    PROXY_CONNECTION_ISSUE = 'proxy_connection_issue'
    CLOUD_LIMIT_REACHED = 'cloud_limit_reached'
    CLOUD_PROFILE_NOT_EXPORTABLE = 'cloud_profile_not_exportable'
    PROFILE_ALREADY_IMPORTED = 'profile_already_imported'
    INCOMPATIBLE_FILE = 'incompatible_file'
    RUNNING_PROFILES_LIMIT_REACHED = 'running_profiles_limit_reached'
    RUNNING_MOBILE_PROFILES_LIMIT_REACHED = 'running_mobile_profiles_limit_reached'
    PROFILE_MINUTES_LIMIT_REACHED = 'profile_minutes_limit_reached'
    DOWNLOADED_CLOUD_PROFILE_BYTES_LIMIT_REACHED = 'downloaded_cloud_profile_bytes_limit_reached'
    FOLDER_NOT_FOUND = 'folder_not_found'
    DATABASE_NOT_FOUND = 'database_not_found'
    VALIDATION_FAILED = 'validation_failed'
    INVALID_REQUEST = 'invalid_request'
    SERVICE_NOT_READY = 'service_not_ready'
    RATE_LIMIT_EXCEEDED = 'rate_limit_exceeded'
    KERNEL_DOWNLOAD_LIMIT_REACHED = 'kernel_download_limit_reached'
    KERNEL_NOT_FOUND = 'kernel_not_found'
    KERNEL_IN_USE = 'kernel_in_use'
    CDP_CONNECTION_FAILED = 'cdp_connection_failed'
    BROWSER_INSTRUMENTATION_DISABLED = 'browser_instrumentation_disabled'
    VNC_NOT_SUPPORTED = 'vnc_not_supported'
    UPLOAD_FAILED = 'upload_failed'
    UNEXPECTED_ERROR = 'unexpected_error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))


