# coding: utf-8

"""
    kameleo-local-api

    You can use the following API endpoints to communicate with the local running Kameleo programmatically.

    The version of the OpenAPI document: 5.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProxyValidationStep(str, Enum):
    """
    ProxyValidationStep
    """

    """
    allowed enum values
    """
    SSH_CONNECTION = 'ssh_connection'
    DIRECT_PING = 'direct_ping'
    DIRECT_HTTPS = 'direct_https'
    PROXY_IPV4 = 'proxy_ipv4'
    PROXY_IPV6 = 'proxy_ipv6'
    PROXY_WEBSITE = 'proxy_website'
    PROXY_LOCATION = 'proxy_location'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProxyValidationStep from a JSON string"""
        return cls(json.loads(json_str))


