<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kameleo.LocalApiClient" Version="5.0.0" />
    <PackageReference Include="PuppeteerSharp" Version="24.39.1" />
  </ItemGroup>

</Project>
