/*
 * kameleo-local-api
 *
 * You can use the following API endpoints to communicate with the local running Kameleo programmatically.
 *
 * The version of the OpenAPI document: 5.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Kameleo.LocalApiClient.Model;

namespace Kameleo.LocalApiClient.Client
{
    /// <summary>
    /// API Exception
    /// </summary>
    public class ApiException : Exception
    {
        /// <summary>
        /// Gets or sets the HTTP status code
        /// </summary>
        /// <value>The HTTP status code.</value>
        public int StatusCode { get; set; }

        /// <summary>
        /// Gets the error code
        /// </summary>
        /// <value>The error code.</value>
        public ErrorCode? ErrorCode => Problem?.ErrorCode;

        /// <summary>
        /// Gets or sets the deserialized <see cref="ProblemResponse"/>
        /// </summary>
        /// <value>The error content (Http response body).</value>
        public ProblemResponse Problem { get; set; }

        /// <summary>
        /// Gets or sets the HTTP headers
        /// </summary>
        /// <value>HTTP headers</value>
        public Multimap<string, string> Headers { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiException"/> class.
        /// </summary>
        public ApiException() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiException"/> class.
        /// </summary>
        /// <param name="statusCode">HTTP status code.</param>
        /// <param name="message">Error message.</param>
        public ApiException(int statusCode, string message) : base(message)
        {
            this.StatusCode = statusCode;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiException"/> class.
        /// </summary>
        /// <param name="statusCode">HTTP status code.</param>
        /// <param name="message">Error message.</param>
        /// <param name="problem">ProblemResponse content.</param>
        /// <param name="headers">HTTP Headers.</param>
        public ApiException(int statusCode, string message, ProblemResponse problem = null, Multimap<string, string> headers = null) : base(message)
        {
            this.StatusCode = statusCode;
            this.Problem = problem;
            this.Headers = headers;
        }
    }
}